import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.scss'
import AuthSessionProvider from '@/context/providers/AuthSessionProvider'
import NextUiProvider from '@/context/providers/nextUi.provider'
import { Toaster } from 'sonner'
import dynamic from 'next/dynamic'
// eslint-disable-next-line @typescript-eslint/promise-function-async
const SWRProvider = dynamic(() => import('@/context/providers/swr.provider'), {
  ssr: false
})
// eslint-disable-next-line @typescript-eslint/promise-function-async
// const Manager = dynamic(() => import('@/context/providers/manager.provider'), {
//   ssr: false
// })

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body className={outfit.className}>
      <AuthSessionProvider>
        <SWRProvider>
          <NextUiProvider>
            <Toaster richColors />
            {children}
          </NextUiProvider>
        </SWRProvider>
      </AuthSessionProvider>
    </body>
  </html>
)

export default RootLayout
