import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import AuthSessionProvider from '@/context/providers/authSession.provider'
import NextUiProvider from '@/context/providers/nextUi.provider'
import { Toaster } from 'sonner'
import SWRProvider from '@/context/providers/swr.provider'
// eslint-disable-next-line @typescript-eslint/promise-function-async

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body className={outfit.className} translate='no'>
      {/* <AuthSessionProvider> */}
        <NextUiProvider>
          {/* <Toaster richColors /> */}
          {children}
        </NextUiProvider>
      {/* </AuthSessionProvider> */}
    </body>
  </html>
)

export default RootLayout
