import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.scss'
import SWRProvider from '@/context/providers/swr.provider'
import AuthSessionProvider from '@/context/providers/AuthSessionProvider'
import NextUiProvider from '@/context/providers/nextUi.provider'

const outfit = Outfit({
  subsets: ['latin'],
  display: 'swap',
  weight: ['200', '300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body className={outfit.className}>
      <SWRProvider>
        <AuthSessionProvider>
          <NextUiProvider>{children}</NextUiProvider>
        </AuthSessionProvider>
      </SWRProvider>
    </body>
  </html>
)

export default RootLayout
